# Generated by Django 2.2 on 2020-08-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='descuento',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.CharField(max_length=50),
        ),
    ]
