# Generated by Django 2.2 on 2020-08-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_auto_20200806_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='idd',
            field=models.IntegerField(default=0),
        ),
    ]
