# Generated by Django 2.2 on 2020-08-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0004_remove_categoria_idd'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='idd',
            field=models.IntegerField(default=0),
        ),
    ]
